### ISSUE TITLE
[Certora] Check not liquidatable position equivalence

### ISSUE THREAD

**Issue by QGarchery** [morpho-org/pre-liquidation#81]
The requires computation was changed in [de168dd](https://github.com/morpho-org/pre-liquidation/pull/77/commits/de168dd6cc41a733023c65d69728d5f9c1ec4981), so now this is exactly the same as in Morpho Blue. But we could still verify that this is equivalent to checking that `ltv <= LLTV`. 

_Originally posted by @QGarchery in https://github.com/morpho-org/pre-liquidation/pull/77#discussion_r1788645020_

**Comment by colin-morpho** [comment]
Done in #37, if I'm not mistaken.

**Comment by QGarchery** [comment]
Nice !

A [similar proof](https://github.com/morpho-org/pre-liquidation/pull/36#issuecomment-2379368039, for the require just next to it actually

**Comment by colin-morpho** [comment]
This done in #89. See https://github.com/morpho-org/pre-liquidation/blob/65ab7ba56c980c572a9108f44a3151a9079e280b/certora/specs/SafeMath.spec#L17.
